# URL of the webpage
fbref_urls = [
    "https://fbref.com/en/squads/18bb7c10/Arsenal-Stats",
    "https://fbref.com/en/squads/8602292d/Aston-Villa-Stats",
    "https://fbref.com/en/squads/4ba7cbea/Bournemouth-Stats",
    "https://fbref.com/en/squads/cd051869/Brentford-Stats",
    "https://fbref.com/en/squads/d07537b9/Brighton-and-Hove-Albion-Stats",
    "https://fbref.com/en/squads/cff3d9bb/Chelsea-Stats",
    "https://fbref.com/en/squads/47c64c55/Crystal-Palace-Stats",
    "https://fbref.com/en/squads/d3fd31cc/Everton-Stats",
    "https://fbref.com/en/squads/fd962109/Fulham-Stats",
    "https://fbref.com/en/squads/b74092de/Ipswich-Town-Stats",
    "https://fbref.com/en/squads/a2d435b3/Leicester-City-Stats",
    "https://fbref.com/en/squads/822bd0ba/Liverpool-Stats",
    "https://fbref.com/en/squads/b8fd03ef/Manchester-City-Stats",
    "https://fbref.com/en/squads/19538871/Manchester-United-Stats",
    "https://fbref.com/en/squads/b2b47a98/Newcastle-United-Stats",
    "https://fbref.com/en/squads/e4a775cb/Nottingham-Forest-Stats",
    "https://fbref.com/en/squads/33c895d4/Southampton-Stats",
    "https://fbref.com/en/squads/361ca564/Tottenham-Hotspur-Stats",
    "https://fbref.com/en/squads/7c21e445/West-Ham-United-Stats",
    "https://fbref.com/en/squads/8cec06e1/Wolverhampton-Wanderers-Stats"
]

sofifa_urls = [
    "https://sofifa.com/team/1/arsenal/",
    "https://sofifa.com/team/2/aston-villa/",
    "https://sofifa.com/team/1943/afc-bournemouth/",
    "https://sofifa.com/team/1925/brentford/",
    "https://sofifa.com/team/1808/brighton-hove-albion/",
    "https://sofifa.com/team/5/chelsea/",
    "https://sofifa.com/team/1799/crystal-palace/",
    "https://sofifa.com/team/7/everton/",
    "https://sofifa.com/team/144/fulham-fc/",
    "https://sofifa.com/team/94/ipswich-town/",
    "https://sofifa.com/team/95/leicester-city/",
    "https://sofifa.com/team/9/liverpool/",
    "https://sofifa.com/team/10/manchester-city/",
    "https://sofifa.com/team/11/manchester-united/",
    "https://sofifa.com/team/13/newcastle-united/",
    "https://sofifa.com/team/14/nottingham-forest/",
    "https://sofifa.com/team/17/southampton/",
    "https://sofifa.com/team/18/tottenham-hotspur/",
    "https://sofifa.com/team/19/west-ham-united/",
    "https://sofifa.com/team/110/wolverhampton-wanderers/"
]


# exclude data points containing these titles
fbref_exclude_keywords = [
    "90", "pct", "gca", "per", "x", "sca",
    "plus", "matches", "games_complete", "average_shot_distance", "goals_assists", "goals_pens", 'tackles_interceptions', 'cards_yellow_red', 'gk_games', 'gk_games_starts', 'gk_minutes', 'gk_goals_against', 'gk_wins', 'gk_ties', 'gk_losses', 'gk_avg_distance_def_actions'
]

fbref_positions = {
    'GK': 'Goalkeeper',
    'DF': 'Defender',
    'MF': 'Midfielder',
    'FW': 'Forward'
}

nations = {
    'ALB': 'Albania',
    'ALG': 'Algeria',
    'ARG': 'Argentina',
    'AUS': 'Australia',
    'AUT': 'Austria',
    'BEL': 'Belgium',
    'BFA': 'Burkina Faso',
    'BIH': 'Bosnia and Herzegovina',
    'BRA': 'Brazil',
    'BRB': 'Barbados',
    'CAN': 'Canada',
    'CIV': 'Ivory Coast',
    'CHI': 'Chile',
    'CMR': 'Cameroon',
    'COD': 'Democratic Republic of the Congo',
    'COL': 'Colombia',
    'CRO': 'Croatia',
    'CRC': 'Costa Rica',
    'CZE': 'Czech Republic',
    'DEN': 'Denmark',
    'ECU': 'Ecuador',
    'EGY': 'Egypt',
    'ENG': 'England',
    'ESP': 'Spain',
    'EST': 'Estonia',
    'FIN': 'Finland',
    'FRA': 'France',
    'GAB': 'Gabon',
    'GAM': 'Gambia',
    'GER': 'Germany',
    'GHA': 'Ghana',
    'GNB': 'Guinea-Bissau',
    'GRE': 'Greece',
    'GRN': 'Grenada',
    'HUN': 'Hungary',
    'IDN': 'Indonesia',
    'IRL': 'Ireland',
    'ISL': 'Iceland',
    'ISR': 'Israel',
    'IRN': 'Iran',
    'IRQ': 'Iraq',
    'ITA': 'Italy',
    'JAM': 'Jamaica',
    'JPN': 'Japan',
    'KOR': 'South Korea',
    'KVX': 'Kosovo',
    'MAR': 'Morocco',
    'MEX': 'Mexico',
    'MLI': 'Mali',
    'MSR': 'Montserrat',
    'NED': 'Netherlands',
    'NIR': 'Northern Ireland',
    'NGA': 'Nigeria',
    'NOR': 'Norway',
    'NZL': 'New Zealand',
    'PAR': 'Paraguay',
    'POL': 'Poland',
    'POR': 'Portugal',
    'ROU': 'Romania',
    'RSA': 'South Africa',
    'SCO': 'Scotland',
    'SEN': 'Senegal',
    'SRB': 'Serbia',
    'SVK': 'Slovakia',
    'SUI': 'Switzerland',
    'SWE': 'Sweden',
    'TOG': 'Togo',
    'TUN': 'Tunisia',
    'TUR': 'Turkey',
    'UKR': 'Ukraine',
    'URU': 'Uruguay',
    'USA': 'United States of America',
    'UZB': 'Uzbekistan',
    'WAL': 'Wales',
    'ZAM': 'Zambia',
    'ZIM': 'Zimbabwe'
}
